# -*- mode: python ; coding: utf-8 -*-

import sys
import os

if sys.platform == "win32":
    from PyInstaller.utils.win32.winutils import MSI

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('assets', 'assets')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='PicPyles',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon='assets/icon.ico',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='PicPyles',
)

if sys.platform == "win32":
    msi = MSI(
        coll,
        name='PicPyles',
        version='1.0.0',
        maintainer='EthernalMesh',
        upgrade_code='{5a617020-4d79-204e-7574-7361636b0000}',
        product_code='{42657374-206f-6620-4672-6565646f6d20}',
        manufacturer='Ethernal Systems',
        description="PicPyles, organize your images into thematic piles.",
        summary_data={
            'author': 'EthernalMesh',
            'comments': 'Generated by PyInstaller',
            'keywords': 'image,organization,piles,zoom,management',
        },
        install_icon='assets/icon.ico',
        targetdir=r'[ProgramFilesFolder]\EthernalSystems\PicPyles',
        shortcuts=[
            ('DesktopShortcut', 'DesktopFolder', 'PicPyles', 'TARGETDIR', '[TARGETDIR]PicPyles.exe', None, None, None, None, None, None, 'TARGETDIR'),
            ('StartMenuShortcut', 'StartMenuFolder', 'PicPyles', 'TARGETDIR', '[TARGETDIR]PicPyles.exe', None, None, None, None, None, None, 'TARGETDIR')
        ],
        license_file='path_to_license.rtf',  # Optional: Include a license agreement
        add_to_path=True,  # Optional: Add the application to the system PATH
    )