name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags, e.g., v1.0.0
    branches:
      - 'automated-build'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.12']  # Specify your Python version

    steps:
    - name: Check out the code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller PicPyles-build.spec
      shell: bash

    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: PicPyles-${{ matrix.os }}-${{ github.sha }}
        path: |
          dist/PicPyles*
        retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Ubuntu artifact
        uses: actions/download-artifact@v4
        with:
          name: PicPyles-ubuntu-latest-${{ github.sha }}
          path: ./dist/ubuntu

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: PicPyles-windows-latest-${{ github.sha }}
          path: ./dist/windows

      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./dist/ubuntu/PicPyles*
            ./dist/windows/PicPyles*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}